# Generated by Django 3.1.7 on 2021-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_name',
            field=models.CharField(max_length=15),
        ),
    ]
