# Generated by Django 3.1.7 on 2021-07-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0002_auto_20210724_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile2',
        ),
    ]
